spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knusearch?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: guestsearch
    password: ghdwn1009G@

  jpa:
    hibernate:
      ddl-auto: update #프로젝트 재시작할떄마다 DB 초기화되는것이 아닌 업데이트
      hbm2ddl:
        auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        show_sql: true
        format_sql: true

  messages:
    basename: messages, names, errors #국제화 파일들

logging.level:
  org.hibernate.SQL: info #trace > debug > info > warn > error
#  org.hibernate.type: trace